# Generated by Django 2.2.2 on 2019-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=100)),
                ('order_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('booking_datetime', models.DateTimeField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('no_of_people', models.IntegerField()),
            ],
        ),
    ]
